
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:8080"
    environment:
      - VITE_PYTHON_ENGINE_URL=http://python-engine:8000
      - VITE_ENABLE_PYTHON_ENGINE=true
    depends_on:
      - python-engine
    volumes:
      - .:/app
      - /app/node_modules

  python-engine:
    build:
      context: ./python_engine
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge
